repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff-format

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff check --fix --select=E,F,I
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest -q
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false
        stages: [pre-push]
