from typing import Any, List, Optional, Union

def clear_figure() -> None: ...
def title(text: str) -> None: ...
def xlabel(text: str) -> None: ...
def ylabel(text: str) -> None: ...
def plot(x: List[float], y: List[float], label: Optional[str] = None) -> None: ...
def xticks(positions: List[float], labels: List[str]) -> None: ...
def show() -> None: ...
