"""create readings & device_room_mappings

Revision ID: 0f90fc7cb614
Revises: 4fba5988d21e
Create Date: 2025-07-27 13:53:10.821856

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f90fc7cb614"
down_revision: Union[str, Sequence[str], None] = "4fba5988d21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_room_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("room", sa.String(), nullable=True),
        sa.Column("start_ts", sa.Float(), nullable=True),
        sa.Column("end_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_room_mappings_device_id"),
        "device_room_mappings",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_room_mappings_end_ts"), "device_room_mappings", ["end_ts"], unique=False
    )
    op.create_index(
        op.f("ix_device_room_mappings_room"), "device_room_mappings", ["room"], unique=False
    )
    op.create_index(
        op.f("ix_device_room_mappings_start_ts"), "device_room_mappings", ["start_ts"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_room_mappings_start_ts"), table_name="device_room_mappings")
    op.drop_index(op.f("ix_device_room_mappings_room"), table_name="device_room_mappings")
    op.drop_index(op.f("ix_device_room_mappings_end_ts"), table_name="device_room_mappings")
    op.drop_index(op.f("ix_device_room_mappings_device_id"), table_name="device_room_mappings")
    op.drop_table("device_room_mappings")
    # ### end Alembic commands ###
