"""create readings table

Revision ID: 4fba5988d21e
Revises: f72c5e62686d
Create Date: 2025-07-27 10:54:18.246828

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fba5988d21e"
down_revision: Union[str, Sequence[str], None] = "f72c5e62686d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Float(), nullable=True),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("pm1", sa.Integer(), nullable=True),
        sa.Column("pm25", sa.Integer(), nullable=True),
        sa.Column("pm10", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_readings_device_id"), "readings", ["device_id"], unique=False)
    op.create_index(op.f("ix_readings_id"), "readings", ["id"], unique=False)
    op.create_index(op.f("ix_readings_ts"), "readings", ["ts"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_readings_ts"), table_name="readings")
    op.drop_index(op.f("ix_readings_id"), table_name="readings")
    op.drop_index(op.f("ix_readings_device_id"), table_name="readings")
    op.drop_table("readings")
    # ### end Alembic commands ###
